export enum EnumsIcon {
  ArrowLeft = 'icon-arrow-left',
  ArrowRight = 'icon-arrow-right',
  Attach = 'icon-attach',
  Chat = 'icon-chat',
  Check = 'icon-check',
  CheckOutline = 'icon-check-outline',
  ChevronUp = 'icon-chevron-up',
  Clock = 'icon-clock',
  Convert = 'icon-convert',
  Cross = 'icon-cross',
  Facebook = 'icon-facebook',
  Iphone = 'icon-iphone',
  LinkedIn = 'icon-linked-in',
  Messanger = 'icon-messanger',
  Minus = 'icon-minus',
  Pin = 'icon-pin',
  Play = 'icon-play',
  Plus = 'icon-plus',
  Twitter = 'icon-twitter',
  Whatsapp = 'icon-whatsapp',
  Youtube = 'icon-youtube',
}

export enum SocialIcon {
  Twitter = 'icon-twitter',
  Whatsapp = 'icon-whatsapp',
  Youtube = 'icon-youtube',
  Facebook = 'icon-facebook',
  LinkedIn = 'icon-linked-in',
  Messanger = 'icon-messanger',
}
