export enum Block {
  BlockHeader = 'blockHeader',
  BlockFooter = 'blockFooter',
  BlockHero = 'blockHero',
  BlockBenefits = 'blockBenefits',
  BlockIntroCarousel = 'blockIntroCarousel',
  BlockConstructiveDecisions = 'blockConstructiveDecisions',
  BlockLatestProjects = 'blockLatestProjects',
  BlockOurClientsTestimonials = 'blockOurClientsTestimonials',
  BlockOurHistory = 'blockOurHistory',
  BlockFormDetail = 'blockFormDetail',
  BlockServices = 'blockServices',
  BlockPricing = 'blockPricing',
  BlockWorkSteps = 'blockWorkSteps',
}
